### PR TITLE
Updates for new beta SDK

### PR DESCRIPTION
**Pull request by maple-klaviyo**

### CODE REVIEW

**Comment by jon-batscha** [comment]
This looks great! One note: looks like the consensus is to go with the following naming for beta SDKs going forward: repo = klaviyo-api-ruby-beta & package = klaviyo-api-beta. Let's create this PR as an internal repo and then push it to a public repo once its ready.

**Comment by dano-klaviyo** [comment]
i think we want this in a separate internal repo as jon suggested: `klaviyo-api-ruby-beta`

**Comment by jon-batscha** [comment]
> i think we want this in a separate internal repo as jon suggested: `klaviyo-api-ruby-beta`

let's make that `klaviyo-api-ruby-beta-internal`

**Comment by maple-klaviyo** [comment]
@dano-klaviyo @jon-batscha ok, sounds good. Will transition shortly.

**Pull request closed without merging**
